server:
  port: 8888

spring:
  http:
    multipart.max-file-size: 25MB
    multipart.max-request-size: 25MB
  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
      write_durations_as_timestamps: false
  data:
    mongodb:
      host: localhost
      port: 27017
      database: pdfupload


files:
  path: /tmp/pdfuploads